# syntax=docker/dockerfile:1.7
# ──────────────────────────────────────────────────────────────────────
# Multi-target build:
#   docker build --target api    -t rag-api .      (no torch; small)
#   docker build --target worker -t rag-worker .   (CPU torch, Detectron2, Tesseract)
#
# Dependencies are installed from hash-pinned lock files
# (requirements/*.lock, generated by scripts/lock.sh). The build fails fast
# if they are missing rather than silently installing unpinned packages.
# ──────────────────────────────────────────────────────────────────────
ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION}-slim-bookworm AS base
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH
RUN groupadd --system --gid 10001 app \
 && useradd --system --uid 10001 --gid app --home-dir /home/app --create-home app
WORKDIR /app

# Helper: install a lock file with hash checking, or fail with instructions.
RUN printf '#!/bin/sh\nset -e\nif [ ! -f "$1" ]; then echo "ERROR: $1 missing. Run ./scripts/lock.sh and commit requirements/*.lock" >&2; exit 1; fi\npip install --require-hashes --no-deps -r "$1"\n' \
      > /usr/local/bin/install-lock && chmod +x /usr/local/bin/install-lock

# ── API ──────────────────────────────────────────────────────────────
FROM base AS api-builder
RUN python -m venv /opt/venv
COPY requirements/ requirements/
RUN install-lock requirements/api.lock

FROM base AS api
RUN apt-get update \
 && apt-get install -y --no-install-recommends curl tini \
 && rm -rf /var/lib/apt/lists/*
COPY --from=api-builder /opt/venv /opt/venv
COPY --chown=app:app config ./config
COPY --chown=app:app src ./src
RUN mkdir -p /app/data/store /tmp/rag-scratch && chown -R app:app /app/data /tmp/rag-scratch
USER 10001
# 8000 = API (via ingress), 9000 = Prometheus metrics (cluster-internal only)
EXPOSE 8000 9000
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD curl -fsS http://localhost:8000/healthz/liveness || exit 1
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", \
     "--proxy-headers", "--forwarded-allow-ips=*", \
     "--timeout-graceful-shutdown", "30", "--no-server-header"]

# ── Worker ───────────────────────────────────────────────────────────
FROM base AS worker-builder
RUN apt-get update \
 && apt-get install -y --no-install-recommends build-essential git \
 && rm -rf /var/lib/apt/lists/*
RUN python -m venv /opt/venv && pip install pip==24.3.1 setuptools==75.6.0 wheel==0.45.1
COPY requirements/ requirements/
RUN install-lock requirements/worker.lock
# Detectron2 is not on PyPI: build from a pinned commit (default: the v0.6 tag
# commit). --no-deps because its runtime deps are in worker.lock with hashes.
ARG DETECTRON2_REF=d1e04565d3bec8719335b88be9e9b961bf3ec464
RUN pip install --no-deps --no-build-isolation \
      "git+https://github.com/facebookresearch/detectron2.git@${DETECTRON2_REF}"

FROM base AS worker
RUN apt-get update \
 && apt-get install -y --no-install-recommends poppler-utils libglib2.0-0 tini \
      tesseract-ocr tesseract-ocr-eng \
 && rm -rf /var/lib/apt/lists/*
COPY --from=worker-builder /opt/venv /opt/venv
COPY --chown=app:app config ./config
COPY --chown=app:app src ./src
RUN mkdir -p /app/data/store /tmp/rag-scratch && chown -R app:app /app/data /tmp/rag-scratch
USER 10001
ENV HOME=/home/app
# Download the PubLayNet config + weights at build time so workers never
# depend on a Dropbox download at runtime. Cached under $HOME/.torch/iopath_cache.
ARG LAYOUT_MODEL_CONFIG=lp://PubLayNet/faster_rcnn_R_50_FPN_3x/config
RUN python -c "import layoutparser as lp; lp.Detectron2LayoutModel('${LAYOUT_MODEL_CONFIG}', extra_config=['MODEL.DEVICE','cpu'])"
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["celery", "-A", "src.tasks.celery_app", "worker", "-Q", "ingestion", "--loglevel=INFO", \
     "--concurrency=2", "--without-gossip", "--without-mingle"]
